#!/bin/bash
set -e

# workaround for linux docker
echo -e "`/sbin/ip route|awk '/default/ { print $3 }'`\tdocker.host.internal" | sudo tee -a /etc/hosts > /dev/null
echo -e "127.0.0.1\tdevbox.localhost" | sudo tee -a /etc/hosts > /dev/null

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
